---
clone:
  depth: 1
kind: pipeline
name: windows amd64 build
platform:
  os: windows
pull: always
steps:
- commands:
  - msbuild windows\ZeroTierOne.sln /m /p:Configuration=Release  /property:Platform=x64
    /t:ZeroTierOne:Rebuild
  - Get-ChildItem
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-builder
  name: build
trigger:
  event:
  - push
  - tag
  - custom
type: docker
