---
clone:
  depth: 1
kind: pipeline
name: windows amd64 build
platform:
  os: windows
pull: always
steps:
- commands:
  - msbuild bytey.vcxproj /p:configuration=debug /p:platform=x64 /p:OutputPath=.
  - Get-ChildItem
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-builder
  name: build
trigger:
  event:
  - push
  - tag
  - custom
type: docker
